version: '3.8'

services:
  agentic-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: agentic-service-prod
    ports:
      - "9510:9510"
    environment:
      # Server configuration
      - API_HOST=0.0.0.0
      - API_PORT=9510
      
      # vLLM connection (update these for your production setup)
      - VLLM_ENDPOINT=http://192.168.6.10:8002
      - VLLM_MODEL=Qwen/Qwen3-32B-FP8
      - AGENTIC_REQUEST_TIMEOUT=30
      
      # Language configuration
      - DEFAULT_LANGUAGE=Chinese
      - SUPPORTED_LANGUAGES=Chinese,English
      - AUTO_DETECT_LANGUAGE=true
      
      # Streaming configuration
      - STREAM_CHAR_BY_CHAR=true
      - FORCE_SMALL_CHUNKS=true
      - NETWORK_STREAMING_OPTIMIZED=true
      - DEBUG_STREAMING=false
      
      # Production mode (disable reload)
      - ENABLE_RELOAD=false
      
      # Storage configuration
      - AGENTIC_DATA_DIR=/app/data
      - AGENTIC_TEMP_DIR=/app/tmp_uploads
      
      # Security (required in production)
      - API_KEY=${API_KEY}
      - MAX_FILE_SIZE_MB=50
      
      # CORS (restrict in production)
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://yourdomain.com}
    
    volumes:
      # Persistent data storage
      - agentic_data:/app/data
      - agentic_temp:/app/tmp_uploads
      
      # Mount production .env file
      - ./.env.prod:/app/.env:ro
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9510/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: agentic-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - agentic-service
    restart: unless-stopped
    profiles:
      - proxy

volumes:
  agentic_data:
    driver: local
  agentic_temp:
    driver: local

networks:
  default:
    driver: bridge
